# fly.toml app configuration file generated for lametric-zenml-app on 2025-07-09T15:16:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lametric-zenml-app'
primary_region = 'ord'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8000'

[processes]
  app = 'python main.py'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
