app = "lametric-zenml-app"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  restart_limit = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "python main.py"